project_name: kkpctl
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: Cedric Kienzler <mail@cedi.dev>
  description: KKPCTL is a CLI Utility for the Kubermatic Kubernetes Platform (KKP)
  homepage: https://github.com/cedi/kkpctl
  license: AGPLv3
  formats:
  - deb
  - rpm
  - apk