name: Go Release

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Install Go tools
      run: |
        go get -u golang.org/x/lint/golint
        go get -u github.com/cweill/gotests/...
        go get -u golang.org/x/tools/cmd/benchcm
        
    - name: Build
      run: make release

    - name: Test
      run: make test

    - name: Vet
      run: make vet

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
